version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: "@sudoo/triforce"
    versions:
    - 2.9.14
    - 2.9.21
  - dependency-name: "@sudoo/mock"
    versions:
    - 1.5.0
